Flowpack:
  JobQueue:
    Common:
      queues:
        'fdmailer-mail-queue':
          className: 'Flowpack\JobQueue\Doctrine\Queue\DoctrineQueue'
          executeIsolated: true
          options:
            defaultTimeout: 50
          releaseOptions:
            priority: 512
            delay: 120

FormatD:
  Mailer:
    QueueAdaptor:
      # Enable or disable asynchronous handling of mails
      enableAsynchronousMails: true

      # E-Mails with attachments may be to big to put into the queue payload as a whole (at least for Doctrine Backend). So we use file cache to store this data.
      serializationCache:
        enabled: true
